spring:
  freemarker:
    template-loader-path: "classpath:/templates"
    suffix: ".ftl"
  datasource:
    url: ${DB_UR:jdbc:postgresql://localhost:5432/post_portal}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}

admin:
  default:
    first_name: ${ADMIN_DEFAULT_FIRST_NAME:Admin}
    last_name: ${ADMIN_DEFAULT_LAST_NAME:Admin}
    age: ${ADMIN_DEFAULT_AGE:20}
    username: ${ADMIN_DEFAULT_USERNAME:admin}
    password: ${ADMIN_DEFAULT_PASSWORD:admin}